---
all:
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_python_interpreter: /usr/bin/python3

  children:

    k8s_masters:
      hosts:
        k8s-master01:
          ansible_host: 78.47.124.35
          keepalived_priority: 110      # highest = MASTER
        k8s-master02:
          ansible_host: 23.88.126.36
          keepalived_priority: 100
        k8s-master03:
          ansible_host: 46.224.167.173
          keepalived_priority: 90

    k8s_workers:
      hosts:
        k8s-worker01:
          ansible_host: 46.224.162.226
        k8s-worker02:
          ansible_host: 46.224.169.8
        k8s-worker03:
          ansible_host: 138.201.184.247

    # Logical groupings for playbook targeting
    k8s_cluster:
      children:
        k8s_masters:
        k8s_workers:
