---
- name: Initialize first master
  ansible.builtin.import_tasks: init-master.yml
  tags: k8s-init
  when: inventory_hostname == k8s_init_node

- name: Join additional masters
  ansible.builtin.import_tasks: join-master.yml
  tags: k8s-join-master
  when:
    - multi_master
    - inventory_hostname != k8s_init_node
    - node_role == "master"

- name: Join worker nodes
  ansible.builtin.import_tasks: join-worker.yml
  tags: k8s-join-worker
  when: node_role == "worker"
