---
apiVersion: kubeadm.k8s.io/v1beta4
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: "172.27.188.100:8443"
    token: "lkhm92.wzdonjhvye1xolki"
    caCertHashes:
      - "sha256:0148073c368e89dab8693cee11b02a541cf51c5efcc949deaf47b3e412450633"
nodeRegistration:
  name: "fxi-am3-kubem02.t.dcbase.tech"
  kubeletExtraArgs:
    - name: "node-ip"
      value: "172.27.188.3"
controlPlane:
  localAPIEndpoint:
    advertiseAddress: "172.27.188.3"
    bindPort: 6443
  certificateKey: "733219499604c0a5a9ef83704643143a37f818e48dce07ec3ab8b950d2518bd9" 