---
- name: Initialize first control-plane node
  ansible.builtin.import_tasks: init.yml
  when: inventory_hostname == k8s_init_node
  tags: cluster-init

- name: Join additional control-plane nodes
  ansible.builtin.import_tasks: join-master.yml
  when:
    - multi_master
    - node_role == "master"
    - inventory_hostname != k8s_init_node
  tags: cluster-join-master

- name: Join worker nodes
  ansible.builtin.import_tasks: join-worker.yml
  when: node_role == "worker"
  tags: cluster-join-worker
