---
- name: Update all packages
  ansible.builtin.import_tasks: update-packages.yml
  tags: update-packages

- name: Disable swap
  ansible.builtin.import_tasks: disable-swap.yml
  tags: disable-swap

- name: Load kernel modules
  ansible.builtin.import_tasks: kernel-modules.yml
  tags: kernel-modules

- name: Set sysctl parameters
  ansible.builtin.import_tasks: sysctl.yml
  tags: sysctl

- name: Install and configure containerd
  ansible.builtin.import_tasks: install-containerd.yml
  tags: containerd

- name: Configure SELinux
  ansible.builtin.import_tasks: selinux.yml
  tags: selinux

- name: Install kubeadm, kubelet and kubectl
  ansible.builtin.import_tasks: install-kube-tools.yml
  tags: kube-tools
